spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FxDb
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect